import { DDEVConfig } from "./config.js";
import { dump } from "js-yaml";

export function renderDDEVConfig(
  appInstallationId: string,
  cfg: Partial<DDEVConfig>,
): string {
  return `# DDEV configuration for mittwald app installation '${appInstallationId}'
# generated by 'mw ddev init-config'
${dump(cfg)}`;
}
