import * as fs from "fs";
import * as path from "path";

/**
 * Known SSH host keys for mittwald clusters.
 *
 * These host keys are embedded in the CLI to allow SSH connections to succeed
 * even in CI/CD environments where the host keys are not pre-populated in
 * ~/.ssh/known_hosts.
 *
 * @see https://github.com/mittwald/cli/issues/1260
 */

/**
 * Map of SSH hostnames to their RSA public keys. Format: "hostname" -> "ssh-rsa
 * AAAA..."
 *
 * These keys are hardcoded to have an authentic source that is independent of
 * the user's environment, so that SSH connections to mittwald clusters can
 * succeed even if the user has not previously connected to those hosts and thus
 * does not have their keys in their own known_hosts file. This is especially
 * important for CI/CD environments where the user's home directory may not be
 * persistent or pre-populated with known host keys.
 *
 * The hostnames used here (e.g. "ssh.fabbenstedt.project.host") are the ones
 * that users will see in SSH connection strings, and they must match the
 * hostnames used in the cluster connection instructions and the SSH config
 * generated by the CLI.
 */
const knownHostKeys: Record<string, string> = {
  "ssh.fabbenstedt.project.host":
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3X+n//34lLBZQsxkqgs1BrUdbqpU3KeF9n+hF4XHIiq2tXm7w6mBVWZlebUjFzKyLMDsaz/1AnUajWPp5CjCA1brEGBrCVoC7nwgmsTw5CMN/66Kb/sr3DQLlqGl5ylv+hF9RVmcqKyBbkPIHCGJm1eG+rwEWX0QMNpTyeQxDzxBLTtvcYebgkrxNEo/bs7YvTFoR+yWHt2MqJMnVDbzy/sm0mZCOFgE/jZ2RwyGmPWat63cZIFWucTZ/C73dmwwOyX/RH9kUSaxBm77UTtNpM23dFLDYyh7dw9I0q/7beTNnMplIlo4YX5+mh2288qcFa6v7N/u/KvlzBmkRcRk7",
  "ssh.schmalge.project.host":
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8DvrhtCe2FQnMPf0caDgTTeyFYMjC/N6xJK9X7OkUgA0A5UPKYQm9/rurJsv9/1TziFYypGF+IMJT3X9/5O9DZMed2hPMmDjEJYYHXZdHT5vSeFf0WuSMWhDEQD757XVA+4ySbyw5+SKsF8HFtuao9moXYMijM+iHp3TWC8be3eJdGkooZundveGIK2xlcgTr3y2LfE9DFMvpx2q4WgDbLrrplvQdJE8eY3Vaz0o251c1PEoOkwCEGQdZxc9XzXHC+SoGV3YPx8WJqhqkM1ayxhOCKJohoN4Nm9H6fcl0tYJCX62+RPi7RRobPzmwbjre8lA2Ibfl3iJVvB830ipj",
  "ssh.vehlage.project.host":
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTi2M1JMT+yL8F6TVyMvVWpDKQJT9tIAfm32gt5FZoJBMI2NM0REh8eTrI0d5nTiaTQSFskKIXMP6kv1UONaFAWIeh6r5+l3GntyOxcakoE9hqsBzQECXyWGMbav47bkLG3JYaTJchlQeeaV05j53LYvVIjw3mdGQKhnhvyJ7T5TjGCZYU2vnzqCtdXHCXMKAcdfh0XtMLjHBn/GJOolH9jDIzjZo2WbwT5S11tZcOnARFoNxelgIuSHwepz+gbgAILEw8UxjwII0M6kXXM0XgyjL/blOjfbkgiy36qMhDwjsQvA2u336R+UfbONajvBs8heygdVmgPsVc5Uz1PqAD",
  "ssh.gestringen.project.host":
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCv2Ojw4TM0+jFyxUgd9EzAAb8mXIzG24yS4V0Md7yphrl9vgZOyEKFhy8KfXAN1qnT1lMQKwfRqthVnfQbbSBGLSrwF1ecbnNtcXX5eAPIP7ycI+PAJJsLmV2099DpXEh9bOrf+vai29OBwtrq1ukFXatocJbC4nKSPWaFuC6yPcgqTTGMZM3ZxVhl6ONtWyao/IoGgTIHiPGxvKqcmqYYU8Zs6VSnYqQ0Sp+v1S5lgECZsDZf+EvBUe53QW8hzqm7z54ef4Qwhn13ODXU7L75LbfKbe0NJdz5higqaiz9BuIMjfbOsBHSTau5suP5fg/3nWsB3KTjl+P1B4Ipow53",
  "ssh.fiestel.project.host":
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmLLYqOR4nTxPpUbayAdhf8BxcbjCdzllS4ERhAOb8tmvm29dKrI9RAoFBwHYZL6fh/GnO3lIXpJI0hPtFifsi7WfdtPxK2rk/D8Ijgp19fqhuVQPnDp8WDbPU6dW7xqlWHsPXLIBdfLvPdgkuyC2FBUYG705P6n048DyC8RTJOA57LZ79W5MiaEfxxSqns1l5amhky1qEUmiuW20Y/QJ3aKxliz+Gw6jdSKfM66mAH/3+JhRyB4oGSPoR3IFTjiba6PLhUYzCj1J9lyGxrNAe8vlJeu/wxFjjCqAC0BIyWE4wuxZdjeCjgCKOFIQAuB3ECFg7Qda5tGLPgG58Ni31",
  "ssh.frotheim.project.host":
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDffzlp4b+mFwmVN2aZrm5pwYj/q6VU6P2NKQWsuft3wgroWbo74p2DAqxG904DrcSZJ1ZBbG9up8hBewbMDgMX5pr+A4Nq0nFS7C3+ctrFfpaRXTGOcqxwKlNlrkqhOHDTRvNcZoFd8DseX07YdM5E9vXcRrEFcO4MNuO6jEKtFXE5KRo4SzMUvHrFpDrL608uvv5LTJynkRGu9zrK8AMgURrIGs4GuhsE1/sSYdtu1+r5sMm4tgCrkfxgEi6weJVG4ZCap6tokg/JojMnExNNnhFvNQEg3QiXHMn4vPh45jldezusodhad51mILMPqSmHlDLwuB0KWmfLQidzT+6j",
  "ssh.isenstedt.project.host":
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA4BkiBXadL4ZCixqcOywUp+l4RnzNEtTTC+Gr+w1dQkXuGg5b6RGJmu+KodFgMyOTPwQMnhj0y0ZQKeHSQVQ4xYLO4kAZNc5AgGPuR9a1cozdLisL8E52fl6YP0ytqOtuH/hsKoIskz1Zl8xUP6mtgVqOT3sZtG29kh3JhngP+JBw94yUs0bOIO84ZPpFbEQ9hmkHMrkHgVoCYpgbV5hnY7tOSyKxWVEQChgXwWe11vpmZzv4XZtnP39bwLbiy4mnOkGqLreXb7kCAljF9hqCOyTaC+mSDdAMsM+qdy7A4SHj6RqCd77QHkmzHJ9gBUnGNX8xMN7+9Rlz3qxK6bqD",
};

/**
 * Path to the mittwald CLI known_hosts file.
 *
 * @param configDir The oclif config directory (typically ~/.config/mw on
 *   Linux/macOS)
 */
function getKnownHostsFilePath(configDir: string): string {
  return path.join(configDir, "known_hosts");
}

/** Returns the known hosts content in SSH known_hosts format. */
export function getKnownHostsContent(): string {
  return Object.entries(knownHostKeys)
    .map(([host, key]) => `${host} ${key}`)
    .join("\n");
}

/**
 * Ensures that the mittwald known_hosts file exists and is up-to-date. Returns
 * the path to the file.
 *
 * @param configDir The oclif config directory (typically ~/.config/mw on
 *   Linux/macOS)
 */
export function ensureKnownHostsFile(configDir: string): string {
  const filePath = getKnownHostsFilePath(configDir);

  // Ensure the directory exists
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true, mode: 0o700 });
  }

  // Write the known hosts file
  const content = getKnownHostsContent();
  fs.writeFileSync(filePath, content + "\n", { mode: 0o600 });

  return filePath;
}

/**
 * Returns SSH command-line options to use the embedded known hosts.
 *
 * These options configure SSH to use our embedded known hosts file as a
 * "global" known hosts file, which is checked in addition to the user's own
 * ~/.ssh/known_hosts file.
 *
 * @param configDir The oclif config directory (typically ~/.config/mw on
 *   Linux/macOS)
 */
export function getSSHKnownHostsFlags(configDir: string): string[] {
  const knownHostsFile = ensureKnownHostsFile(configDir);
  return ["-o", `GlobalKnownHostsFile=${knownHostsFile}`];
}

/**
 * Returns the SSH options string for use with rsync's --rsh flag or scp.
 *
 * @example
 *   // For rsync:
 *   `--rsh "ssh ${getSSHKnownHostsArgsString(configDir)}"`;
 *
 * @example
 *   // For scp:
 *   `scp ${getSSHKnownHostsArgsString(configDir)} source dest`;
 *
 * @param configDir The oclif config directory (typically ~/.config/mw on
 *   Linux/macOS)
 */
export function getSSHKnownHostsArgsString(configDir: string): string {
  const knownHostsFile = ensureKnownHostsFile(configDir);
  return `-o GlobalKnownHostsFile=${knownHostsFile}`;
}
