import React, { FC } from "react";
import { Box, Text } from "ink";
import { CommandHint } from "./CommandHint.js";

interface ContainerManagementCommandsProps {
  containerIdentifier: string;
}

const infoColor = "blueBright";

/**
 * ContainerManagementCommands is a React functional component that provides
 * commands and instructions for interacting with a specific container.
 *
 * This component displays a set of command hints, allowing users to:
 *
 * - Connect to a container via SSH.
 * - View logs generated by the container.
 * - Execute specific commands within the container.
 *
 * The displayed commands are dynamically generated based on the
 * `containerIdentifier` prop, which identifies the container to manage.
 *
 * @property string ContainerIdentifier - The unique identifier of the container
 *   to manage. This is included in the commands displayed by the component.
 */
export const ContainerManagementCommands: FC<
  ContainerManagementCommandsProps
> = ({ containerIdentifier }) => {
  return (
    <>
      <Box marginTop={1}>
        <Text bold color={infoColor}>
          🔧 Manage Your Container:
        </Text>
      </Box>
      <CommandHint
        command={["mw", "container", "ssh", containerIdentifier]}
        description="Connect to the container via SSH to run commands interactively"
      />
      <CommandHint
        command={["mw", "container", "logs", containerIdentifier]}
        description="View the container's log output and monitor its activity"
      />
      <CommandHint
        command={["mw", "container", "exec", containerIdentifier, "<command>"]}
        description="Execute a specific command inside the running container"
      />
    </>
  );
};
