name: Compilation & Unit Tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile TypeScript
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: yarn
      - run: yarn compile

  # This is necessary because we also advertise "npm install -g" as an installation
  # method. Even though we're using yarn ourselves, npm must be able to resolve
  # this package to an installable set of dependencies.
  npm-resolvable:
    strategy:
      matrix:
        node_version: [20, 22, 24]
    runs-on: ubuntu-latest
    name: Test if dependencies are resolvable without errors
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm install

  licenses:
    runs-on: ubuntu-latest
    name: Check license compatibility
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: yarn test:licenses

  lint:
    runs-on: ubuntu-latest
    name: Run linters
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: yarn test:format

  tests:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: yarn test:unit

  readme:
    name: Assert README.md is up-to-date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: yarn compile
      - run: yarn test:readme

  docker:
    name: Build and run docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: yarn compile
      - run: npx oclif pack tarballs --targets=linux-x64
      - run: docker build --build-arg PKG_SOURCE=dist -t mittwald/cli:testing .
      - run: docker run --rm mittwald/cli:testing --help
